export interface IPropertybase{
    Id:number;
    SellRent:number|null;
    Name:string;
    PType:string;
    FType:string;
    Price:number  | null; 
    BHK:number;
    BuiltArea:number;
    City:string;
    RTM:number;
    Address:string;
    ImageUrl:string;
    Landmark:string;
    Floor:number;
    TotalFloors:number;
    Age:number;
    Description:string;
    Type : string; 
    FloorNo?: number;
    TotalFloor?: number;
    AOP?: number;
    Bathrooms?: number;
    Posession?: string;
    CarpetArea?: number;
    MainEntrance?: string;
    Security?: number;
    Maintenance?: number;
    PostedOn?: string;
    Image?: string;
    Photos?: string[];
};