export interface IPropertybase{
    Id:number;
    SellRent:number;
    Name:string;
    PType:string;
    FType:string;
    Price:number  | null; 
    BHK:number;
    BuiltArea:number;
    City:string;
    RTM:number;
    Address:string;
    ImageUrl:string;
    Landmark:string;
    Floor:number;
    TotalFloors:number;
    Age:number;
    Description:string;
    Type : string; 
};