import { IPropertybase } from './IPropertybase';

export class Property implements IPropertybase {
    Id: number = 0;
    SellRent: number | null = null;
    SellOrBuy: string = '';
    Name: string = '';
    PType: string = '';
    FType: string = '';
    Price: number | null = null;
    BHK: number = 0;
    BuiltArea: number = 0;
    CarpetArea?: number;
    Address: string = '';
    Address2?: string;
    City: string = '';
    FloorNo?: number;
    TotalFloor?: number;
    RTM: number = 0;
    AOP?: number;
    MainEntrance?: string;
    Security?: number;
    GatedCommunity?: number;
    Maintenance?: number;
    PossessionDate?: string;
    ImageUrl: string = '';
    Description: string = '';
    PostedOn: string = '';
    PostedBy: number = 0;
    LastUpdate?: string;
    Type: string = '';
    Floor: number = 0;
    TotalFloors: number = 0;
    Age: number = 0;
    Landmark: string = '';
    Bathrooms?: number;
    Posession?: string;
    Image?: string;
    Photos?: string[];
}
